# Generating german doctor reviews with a GPT-2 model
## Fine tuning of a pretrained **Hugging Face** transfomer decoder
In this notebook we will be using a GPT-2 mdoel that was fine-tuned to synthesize doctor reviews mimiking actual patients' text comments.

A detailed description of the **German language reviews of doctors by patients 2019** dataset can be found [here](https://data.world/mc51/german-language-reviews-of-doctors-by-patients)


For this exercise, we will use the [**Hugging Face**](https://huggingface.co/) implementation of transformers for PyTorch. Transformers provides a general architecture implementation for several state of the art models in the natural language domain.

NOTE: This notebook and its implementation is heavily influenced by the [data-drive](https://data-dive.com/) *Natural Language Processing of German texts* blog post

In [15]:
!pip install -U transformers==4.42.4

Requirement already satisfied: transformers==4.42.4 in /usr/local/lib/python3.12/dist-packages (4.42.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.4) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.4) (0.34.4)
Requirement already satisfied: numpy<2.0,>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.4) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.4) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.4) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.4) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.4) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.4) (0.6.2)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.4) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.4) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.42.4) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.42.4) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.42.4) (1.1.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.4) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.4) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.4) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.4) (2025.8.3)

In [16]:
import pandas as pd
import torch

from transformers import AutoTokenizer, GPT2LMHeadModel

pd.options.display.max_colwidth = 600
pd.options.display.max_rows = 400

## Setting up the decoder model
HuggingFace's transfomer library allows for conviniently loading pre-configured text tokenizers and pre-trained models from local resources.

Here we will be using a tokenizer and a GPT-2 model that was pre-trained on the doctor review dataset

In [17]:
!rm -r gpt2_doctorreview_finetuned* __MACOSX
!gdown https://drive.google.com/uc?id=13wbf5bsLmvRFD-AgbmruWo6bdiyjkwd9 -O gpt2_doctorreview_finetuned.zip
!unzip gpt2_doctorreview_finetuned.zip

Downloading...
From (original): https://drive.google.com/uc?id=13wbf5bsLmvRFD-AgbmruWo6bdiyjkwd9
From (redirected): https://drive.google.com/uc?id=13wbf5bsLmvRFD-AgbmruWo6bdiyjkwd9&confirm=t&uuid=cff1af85-a09a-4e8a-be8f-67187877a7a4
To: /content/gpt2_doctorreview_finetuned.zip
100% 463M/463M [00:08<00:00, 56.8MB/s]
Archive:  gpt2_doctorreview_finetuned.zip
   creating: gpt2_doctorreview_finetuned/
  inflating: gpt2_doctorreview_finetuned/.DS_Store
  inflating: __MACOSX/gpt2_doctorreview_finetuned/._.DS_Store
   creating: gpt2_doctorreview_finetuned/tokenizer/
   creating: gpt2_doctorreview_finetuned/model/
  inflating: gpt2_doctorreview_finetuned/tokenizer/added_tokens.json
  inflating: __MACOSX/gpt2_doctorreview_finetuned/tokenizer/._added_tokens.json
  inflating: gpt2_doctorreview_finetuned/tokenizer/tokenizer_config.json
  inflating: __MACOSX/gpt2_doctorreview_finetuned/tokenizer/._tokenizer_config.json
  inflating: gpt2_doctorreview_finetuned/tokenizer/special_tokens_map.json
  inflating: __MACOSX/gpt2_doctorreview_finetuned/tokenizer/._special_tokens_map.json
  inflating: gpt2_doctorreview_finetuned/tokenizer/tokenizer.json
  inflating: __MACOSX/gpt2_doctorreview_finetuned/tokenizer/._tokenizer.json
  inflating: gpt2_doctorreview_finetuned/tokenizer/merges.txt
  inflating: __MACOSX/gpt2_doctorreview_finetuned/tokenizer/._merges.txt
  inflating: gpt2_doctorreview_finetuned/tokenizer/vocab.json
  inflating: __MACOSX/gpt2_doctorreview_finetuned/tokenizer/._vocab.json
  inflating: gpt2_doctorreview_finetuned/model/config.json
  inflating: __MACOSX/gpt2_doctorreview_finetuned/model/._config.json
  inflating: gpt2_doctorreview_finetuned/model/tf_model.h5
  inflating: __MACOSX/gpt2_doctorreview_finetuned/model/._tf_model.h5

In [18]:
tokenizer = AutoTokenizer.from_pretrained('gpt2_doctorreview_finetuned/tokenizer')
model = GPT2LMHeadModel.from_pretrained('gpt2_doctorreview_finetuned/model', from_tf=True)
# Set model to evaluation mode
model.eval()

All TF 2.0 model weights were used when initializing GPT2LMHeadModel.

Some weights of GPT2LMHeadModel were not initialized from the TF 2.0 model and are newly initialized: ['lm_head.weight', 'lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50269, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2SdpaAttention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50269, bias=False)
)

## Generating doctor reviews
The model has been conditioned to be able to control if positive or negative reviews should be generated.

As an auto-regressive model the sequence is generated by building up from the passed input sequences. We can use this to control the polarity of the review by passing either the token for positive or for negative reviews

In [19]:
POS_TOKEN = "<|review_pos|>"
NEG_TOKEN = "<|review_neg|>"

### Simple greedy search
Let's implement our own greedy-search-based text generator. Generation happens in a loop where one token is generated at a time. Token with highest probability is select in each iteration.

**HINT**:
- Useful functions for this exercise:
 - [`torch.argmax`](https://pytorch.org/docs/stable/generated/torch.argmax.html)
 - [`torch.cat`](https://pytorch.org/docs/stable/generated/torch.cat.html)
- PyTorch tensors can be sliced using the same syntax as with Numpy Array
 - Use slicing to retrieve specific tensor parts

In [20]:
def generate_greedy(inputs:str, max_length=15):
    #Generates a text sequence from an input str using a greedy search
    input_ids = tokenizer.encode(inputs, return_tensors='pt')

    ##########################
    ## YOUR CODE HERE START ##
    ##########################

    # loop until the max_length is reached
    for __ in range(max_length):

        # Use no_grad to disable gradient calculation for inference
        with torch.no_grad():
            outputs = model(input_ids)
            logits = outputs.logits

        # retrieve the predicted logits for the *last* token
        # Dimensions are [batch_size, input_tokens, vocab_size]
        next_token_logits = logits[:, -1, :]

        # Select the token with the highest probability
        next_token = torch.argmax(next_token_logits, dim=-1)

        # We have to expand the dimension of the next token to match
        # the shape of input_ids
        next_token = next_token.unsqueeze(-1)

        # Now we need to add the next_token to the previous ones.
        # Concat input_ids with the next_token
        input_ids = torch.cat([input_ids, next_token], dim=1)

    output_ids = input_ids.squeeze().tolist()

    ### Use your tokenizer to decode the output ids into text
    decoded = tokenizer.decode(output_ids)

    ##########################
    ## YOUR CODE HERE END ##
    ##########################
    return decoded

When you invoke you greedy search implementation you will get a generated text conditioned on the beginning of the input-text.

Using `POS_TOKEN` will increase the likelihood to generate a positive text. While using `NEG_TOKEN` will result in a rather negative text.

In [21]:
generate_greedy(POS_TOKEN + ' Ich', max_length=15)

'<|review_pos|> Ich bin seit Jahren bei Dr. Heuer in Behandlung und bin sehr zufrieden.'

### More advanced text generation
So far so good. Now we understand how text can be generated.

However we ignore when our model predicts EOS (end-of-sentence). What would be neccessary to incoorporate this in our function?

What if we would want to generate multiple different review comments?
Did you generate long reviews? Have you started to see repetitions in the generated output? Why is that?

Luckily the Hugging Face implementation offers various ways for us to generate higher quality reviews.

#### Greedy search
The following code can be used to generate text using a greedy search algorithm:

In [22]:
# encode context the generation is conditioned on
input_ids = tokenizer.encode(POS_TOKEN, return_tensors='pt')

# generate text until the output length
# (which includes the context length) reaches 50
greedy_outputs = model.generate(
    input_ids,
    max_length=50,
    num_return_sequences=3,
    )

genrated_reviews = [{'generated_text': tokenizer.decode(output, skip_special_tokens=True)}
                    for output in greedy_outputs]
pd.DataFrame(genrated_reviews)

                                                                                                                                                                                                                                                 generated_text
0           Er ist echt der beste Arzt dem ich je begegnet bin!!! Ich war viele Jahre bei ihm in Behandlung und er hat mich immer gut beraten ich verstehe die negative Bewertung nicht, aber ich habe mich noch nie so wohl gefühlt. Er versucht zu helfen und
1   Endlich habe ich den perfekten Zahnarzt gefunden. Nach einer Odyssee durch diverse andere Zahnärzte, mit denen ich nicht zufrieden war, die mir die Schmerzen genommen haben. Herr Jank ist ein toller Zahnarzt, den ich nur empfehlen kann. Die Behandlung
2                                                                     Ein sehr zugewandter und freundlicher Arzt, kann gut zuhören und die Ergebnisse gut erklären. Wir waren dort zur Feindiagnostik Ultraschall. Er ist auf dem Gebiet der Urologie sehr gut.

#### Beam search
Beam search can be considered as an alternative. At each step of generating a token, a set of top probability tokens are kept as part of the beam instead of just the highest-probability token. The sequence with the highest overall probability is returned at the end of the generation.

What do the parameters `no_repeat_ngram_size` and `temperature` control?

Generating text using beam search is done like this:

In [23]:
beam_outputs = model.generate(
    input_ids,
    max_length=50,
    num_beams=7,
    no_repeat_ngram_size=3,
    num_return_sequences=3,
    early_stopping=True,
    temperature=0.7
)

genrated_reviews = [{'generated_text': tokenizer.decode(output, skip_special_tokens=True)}
                    for output in beam_outputs]
pd.DataFrame(genrated_reviews)

                                                                                                           generated_text
0        Ich bin sehr zufrieden mit der Behandlung. Die Ärztin ist sehr kompetent und nimmt sich Zeit für ihre Patienten.
1         Ich bin sehr zufrieden mit der Behandlung. Die Ärztin ist sehr kompetent und nimmt sich Zeit für die Patienten.
2   Ich bin sehr zufrieden mit der Behandlung. Die Ärztin ist sehr freundlich und nimmt sich viel Zeit für die Patienten.

#### High level pipeline
The easiest way to to use the model is to use HuggingFaces transformer `pipeline` implementation to encapsulate the previously loaded `model` and `tokenizer`.

The documentation for the [**pipeline**](https://huggingface.co/transformers/main_classes/pipelines.html) abstraction describes how to do the setup.

While being able to generate reviews with very high fiddelity, it's also the slowest approach. Can you find out why?

In [24]:
from transformers import pipeline

In [25]:
##########################
## YOUR CODE HERE START ##
##########################
# build a transformer-pipeline
# to generate text using the
# previously loaded model and tokenizer

review_generator = pipeline(
  "text-generation",
  model=model,
  tokenizer=tokenizer,
  device=0 if torch.cuda.is_available() else -1  # Use GPU if available
)

##########################
## YOUR CODE HERE END   ##
##########################

In [26]:
pos_generated_reviews = review_generator(POS_TOKEN, max_length=50, num_return_sequences=3)
pd.DataFrame(pos_generated_reviews)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.

                                                                                                                                                                                                                                                                     generated_text
0                                                                                                                          <|review_pos|> Sehr freundlich und kompetent, nimmt sich die Zeit, hört zu und erklärt auch. Ich habe vollstes Vertrauen in Dr. Schneider und sein Team.
1  <|review_pos|> Ich habe bisher nur gute Erfahrungen in dieser Praxis gemacht. Man wird freundlich empfangen und fühlt sich sehr gut aufgehoben. Die Ärztin nimmt sich Zeit, geht auf einen ein und strahlt eine so lockere Freundlichkeit aus, dass man sich in den guten Händen
2                                                <|review_pos|> Dr. Ewig ist ein fachlich sehr kompetenter und vertrauenswürdiger Arzt. Bei ihm ist man in sehr guten Händen. Er nimmt sich viel Zeit für Patienten, wodurch man dann nicht mit Samthandschuhen die Beine vergisst!

In [27]:
neg_generated_reviews = review_generator(NEG_TOKEN, max_length=50, num_return_sequences=3)
pd.DataFrame(neg_generated_reviews)

                                                                                                                                                                                                                                                         generated_text
0  <|review_neg|> Ich habe schon viele Frauenärzte erlebt aber hier bin ich eigentlich super zufrieden. Dr. Velten wirkt oft ziemlich reserviert und ist wenig einfühlsam, nimmt Sorgen nicht Ernst und erklärt kaum etwas. Wenn man fragen hat, macht er sehr schnell,
1    <|review_neg|> Dr Schleyer stellte einen Meningusfraktur fest. Die Diagnose ergab jedoch das gleiche Ablaufen, was er leider nicht wollte und als Folge auf eine Beinlängenfehler meines Knie sagte er ohne Röntgen auf seinem Schreibtisch sitzen zu können. Nach
2   <|review_neg|> Ich habe mehrere Jahre lang Probleme mit meiner Hüfte durch ein Hautkrebsscreening. Dr.. wirkte auf mich nicht besonders interessiert oder gehetzt. Die Diagnose fiel aus dem Grunde, dass er sich für ein umfassendes Beratungsgespräch entschieden

# Congratulation
You have explored different ways to generate text with a GPT-2-Transformer model using PyTorch